### ISSUE TITLE
How to implement fingerprinting for dynamic asset url

### ISSUE THREAD

**Issue by zetas** [rickharrison/broccoli-asset-rev#24]
Hi, I'm having some trouble with broccoli-asset-rev in ember-cli. 

My use-case is loading a logo from the database like so:

``` handlebars
<img {{bind-attr src=logo}}/>
```

The issue is the fingerprint for that image is not appended at runtime and so in production, none of these assets work. It's looking for /assets/images/bar023.jpg but the actual file is now /assets/images/bar023-ad232dd232d23423.jpg

Of course I can disable fingerprinting, and that's what I've done in the meantime but I really would like to be able to use it, just somehow append the fingerprint in the template or maybe as a property on the controller? 

Thanks,
David

**Comment by mksplg** [comment]
I stumbled over the same problem. The workaround I've used now is async loading the assetMap.json and injecting a dependency in an initializer. It provides an `assets.resolve(localPath)` function.
```javascript
import Ember from 'ember';

export function initialize(container, application) {
  application.deferReadiness();

  var AssetMap = Ember.Object.extend();

  var promise = new Ember.RSVP.Promise(function(resolve, reject) {
    Ember.$.getJSON('assets/assetMap.json', resolve).fail(reject);
  });

  promise.then(function(assetMap) {
    AssetMap.reopen({
      assetMap: assetMap,
      resolve: function(name) {
        return assetMap.assets[name];
      }
    });
  }, function() {
    AssetMap.reopen({
      resolve: function(name) {
        return name;
      }
    });
  }).then(function() {
    container.register('assetMap:main', AssetMap, {singleton: true});
    application.inject('component', 'assets', 'assetMap:main');
    application.advanceReadiness();
  });
}

export default {
  name: 'asset-map',
  initialize: initialize
};
```
This can then be used with `this.assets.resolve('img/posters/' + this.get('id') + '.jpeg')`. Hope this helps someone else.

**Comment by marlonmantilla** [comment]
Hi everyone, I'm new to Ember here ... Can't see assetMap.json file on my project neither in my dist folder. Any ideas of how to achieve this in ember-cli ?

**Comment by rickharrison** [comment]
Use `generateAssetMap` as shown in the readme https://github.com/rickharrison/broccoli-asset-rev

**Comment by ehubbell** [comment]
We're running into a similar issue. For our application, we're generating dynamic images from a helper and then injecting the correct one into a couple templates. 

The use-case is pretty simple. We're checking the type of credit card a user has on file with us, then we're generating a path to the correct image asset (in our public folder) to display next to the card at checkout and in a user's settings. 

Due to fingerprinting, our app is unable to find the asset path since we're generating the path outside our templates and stylesheets.We have a workaround for now however it'd be nice if we could fingerprint images from files outside our templates & stylesheets.

**Comment by kgish** [comment]
@mksplg +1

**Comment by wehlutyk** [comment]
@mksplg did you find a way to get the assetMap at compile-time?

My use-case is with [ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy/), which sends all the assets to (e.g.) S3, and only `index.html` to your server, so there's no simple access to `assetMap.json` (deployment will send it fingerprinted to S3). I stumbled upon [ember-cli-inject-asset-map](https://github.com/jcaffey/ember-cli-inject-asset-map) but there might be some cleanup to do there.

**Comment by kgish** [comment]
This is my helper `asset-resolve`
```
import Ember from 'ember';

export function assetResolve(asset) {
    var fn = Ember.container.lookup('assetMap:main');
    var res = asset;
    if (fn) {
        var a = fn(asset);
        if (a) { res = a; }
    }
    return res;
}

export default Ember.Helper.helper(assetResolve);
```

**Comment by Fryie** [comment]
I have chosen a slightly different solution. I have a ```config/cdn.json``` file, and then I just read it in two places:
```
// ember-cli-build.js
var cdnConfig = JSON.parse(require('fs').readFileSync('config/cdn.json'));
var cdnPath = cdnConfig[process.env.EMBER_ENV];

var app = new EmberApp(defaults, {
  fingerprint: {
    prepend: cdnPath
})

// config/environment.js
var cdnConfig = JSON.parse(require('fs').readFileSync('config/cdn.json'));
ENV.APP.CDN_PATH = cdnConfig[process.env.EMBER_ENV];
```

Yes, that duplicates the part of reading the file, but the stuff that is actually more likely to change, the paths themselves, are stored in one location.

With this, I can build a simple util:
```
import ENV from 'volders/config/environment';
export function assetPath(asset) {
  return `${ENV.APP.CDN_PATH}assets/${asset}`;
}
```

**Comment by RuslanZavacky** [comment]
@Fryie so you don't use fingerprinting? But just pre-pending URL? How you deal with client side assets caching?

**Comment by Fryie** [comment]
I do, I just excluded it from this example because it depends on a
"isProductiobLikeBuild" var
Am 01.10.2015 16:17 schrieb "Ruslan Zavacky" <notifications@github.com>:

**Comment by Fryie** [comment]
Oh I see what you mean now. Yeah, with fingerprinting you'd also need the specific asset fingerprint, so that solution won't work. I totally missed that.

**Comment by Fryie** [comment]
you could specify a custom fingerprint hash: http://www.ember-cli.com/user-guide/#asset-compilation
that could be the git commit, for example

**Comment by seawatts** [comment]
@wehlutyk I am doing the same thing with ember-cli-deploy. Did you find a solution?

**Comment by wehlutyk** [comment]
@seawatts unfortunately nothing implemented yet. I think the way to go is what's explained as option 2 in [this comment](https://github.com/ember-cli/ember-cli-deploy/issues/219#issuecomment-143066209), but I haven't had the time to implement it. My next free slot to do it is in a month or two (but I won't make any promises -- if you know how to do it feel free :) ).

(In the meantime, since I only have 4 dynamic url assets, whenever they change I build once, then copy those particular fingerprints by hand from `assetMap.json` into my app code, then build again.)

**Comment by Fryie** [comment]
There is some discussion [over here](http://discuss.emberjs.com/t/resolving-fingerprinted-assets-using-generateassetmap/8783/8). Unfortunately, it is not at all easy to come up with a working solution. In fact, we had to go through several iterations to have a real bug-free solution.

you'll want the
```
fingerprint: {
      ...
      generateAssetMap: true,
      fingerprintAssetMap: true
    },
```
option, so your asset map is generated (and uploaded), and so it's fingerprinted as well (otherwise a client might retrieve an outdated asset map from the cache!).

Then, in your code you can retrieve the asset map via `assets/assetMap.json`. Ember CLI will automatically replace this string with the correct URL to the fingerprinted asset map in the production build. Then follow a similar procedure as outlined [here](http://discuss.emberjs.com/t/resolving-fingerprinted-assets-using-generateassetmap/8783/5?u=fryie).

**Comment by devinrhode2** [comment]
Also encountered this issue. I have image names coded directly into a plain javascript file that provides some data for the ui (app/ui-data.js), but I dynamically create the full paths for each url in my ui-data object. Just hard coding the full asset paths, and removing my code dynamically creates them, fixes the issue for me.

The full path makes broccoli-asset-rev recognize them and rewrites them, apparently in any source file anywhere in the ember app.

**Comment by RuslanZavacky** [comment]
@devinrhode2 I wrote an article about fingerprinting - https://medium.com/@ruslanzavacky/ember-cli-fingerprinting-and-dynamic-assets-797a298d8dc6 and also created a relevant addon that helps to solve fingerprinting issues - https://github.com/RuslanZavacky/ember-cli-ifa. Its still not ideal, but at least its doing it from the "box".

**Comment by carrotalan** [comment]
Sounds like there is no real resolution to this still.

Dynamic URLs are a huge part of large, production systems. We can implement the workarounds, but I would suggest this must be on a high priority of fixes for your next release (please!)

**Comment by RuslanZavacky** [comment]
@carrotalan you can easily use an addon that I've provided. Works well and for large production systems :)
